apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: frontend-server
  namespace: myapp
spec: 
  selector: 
    matchLabels: 
      app: frontend 
  replicas: 1
  template: 
    metadata: 
      labels: 
        app: frontend  
    spec: 
      containers: 
        - name: frontend 
          image: esjwoo/mini-front:latest
          ports: 
            - containerPort: 443
          env:
            - name: NODE_ENV
              value: "production"
            - name: JWT_SECRET
              value: "thisIsMySecretKey"
            - name: PORT
              value: "443"
            - name: BACKEND_HOST
              value: "backend-service"
            - name: BACKEND_PORT
              value: "8000"
            - name: CHATBOT_HOST
              value: "backend-service"
            - name: CHATBOT_PORT
              value: "8000"
            - name: CLIENT_ID
              value: "7hI4IYFb2ETaTtFDe95B"
            - name: CLIENT_SECRET
              value: "1Yt9Y3DRw9"
            - name: REDIRECT_URI
              value: "https://midteam1.lion.nyhhs.com/naverlogin/login"
            - name: JAVASCRIPT_APPKEY
              value: "4b5ecb6281d617d7a988622ad24d251b"
--- 
apiVersion: v1 
kind: Service 
metadata: 
  name: frontend-service
  namespace: myapp
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 9443
      targetPort: 443
      nodePort: 30001