apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: mid2-team1-hpa
  namespace: myapp  # 네임스페이스 상황에 맞게 변경
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend-server
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 40